databases:
  - name: alertgov-db
    databaseName: alertgov
    user: alertgov

services:
  - type: web
    name: alertgov-santa-fe-leyte
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "python manage.py migrate --noinput && python setup_demo_data.py && gunicorn alertgov.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: alertgov-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://alertgov-santa-fe-leyte.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://alertgov-santa-fe-leyte.onrender.com"
      - key: CLOUDINARY_CLOUD_NAME
        value: "dpjhmjhtv"
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
